# Site settings
# These are the main settings for your Jekyll site

title: "Ryker Tracy"
description: "A centralized, visually friendly display of my work on GitHub."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rykertracy.github.io" # the base hostname & protocol for your site

# Author settings
author:
  name: "Ryker Tracy"
  email: "rykertracy@example.com"
  github: "rykertracy"
  bio: "Data Scientist, Geoscientist, and a Lifelong Learner"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-remote-theme

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single"
      author_profile: true

# Social
social:
  github: rykertracy
  linkedin: "ryker-tracy-737024125"

# Other settings
markdown: kramdown
highlighter: rouge
